Develop ROS2 lightbar Driver
usdot-fhwa-stol/carma-lightbar-driver pull request #58
Opened 2022-07-31 19:03 UTC by aswath1

# PR Details
## Description
Develop ROS2 lightbar Driver

## Related Issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/1867

## Motivation and Context
Modify light bar driver to  ROS2

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-01 06:12 UTC, MishkaMN requested changes

2022-08-01 06:12 UTC, MishkaMN commented on lightbar_driver/include/lightbar_driver/lightbar_driver_application.hpp
>  #define HTTP_HOSTNAME     "192.168.88.28"
I guess since we have it in config now, we can remove this?

2022-08-01 06:12 UTC, MishkaMN commented on lightbar_driver/src/lightbar_driver_application.cpp
> +    lightbar_ctrl_.configureHTTP(host_name,port,user,password);
This should be inside `handle_on_configure()`

2022-08-01 06:12 UTC, MishkaMN commented on lightbar_driver/src/lightbar_driver_application.cpp
> +        driver_discovery_timer_ = this->create_wall_timer(std::chrono::milliseconds(500),
Let's make it 1000.
it used to be 1 sec here:
https://github.com/usdot-fhwa-stol/carma-utils/blob/develop/cav_driver_utils/src/driver_application/driver_application.cpp#L58

2022-08-01 06:12 UTC, MishkaMN commented on lightbar_driver/src/lightbar_driver_application.cpp
> +        lightbar_timer_ = this->create_wall_timer(std::chrono::milliseconds(500),
`config_.status_update_rate` is in hz. So here instead of 500, we make it `1000/config_.status_update_rate`

2022-08-01 06:15 UTC, MishkaMN commented
Also please create another in PR in carma-config, which is where this node is called.
ROS1 used to be called here (this is exampe for pacifica. All other vehicle types also have it in their own respective folder)
https://github.com/usdot-fhwa-stol/carma-config/blob/develop/chrysler_pacifica_ehybrid_s_2019/drivers.launch#L60-L65
So remove it from there, and call it in `drivers.launch,py`

2022-08-01 19:57 UTC, MishkaMN requested changes
add following to both `target_link_libraries`

'${PUGIXML_LIBRARIES}
 ${CURL_LIBRARIES}'

2022-08-01 19:57 UTC, MishkaMN commented on lightbar_driver/CMakeLists.txt
> +  ${catkin_INCLUDE_DIRS}
delete this

2022-08-02 16:13 UTC, MishkaMN submitted a review, later dismissed

2022-08-03 12:31 UTC, msmcconnell requested changes

2022-08-03 12:31 UTC, msmcconnell commented on lightbar_driver/launch/lightbar_driver_node_launch.py
> +                    parameters=[ ]
Added LaunchConfigurations need to be passed as parameters

2022-08-03 15:08 UTC, msmcconnell approved these changes

2022-08-03 18:55 UTC, merged